# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               3 Diagrams per Page
tagline:             Here will be my blog one day...
description:         'My blog!'
url:                 http://felix11h.github.io/
baseurl:             ''


# About/contact
author:
  name:              Felix Z. Hoffmann
  url:               http://felix11h.github.io/
  email:             felix11h.dev@gmail.com

# Custom vars
version:             1.0.0

gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

