# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               3 Diagrams per Page
tagline:             
description:         Personal blog of Felix Z. Hoffmann on computational neuroscience, mathematics, open science and the tools he uses keep organizes his thoughts and ideas. 
url:                 http://felix11h.github.io/
baseurl:             /blog

# About/contact
author:
  name:              Felix Z. Hoffmann
  url:               http://felix11h.github.io/
  email:             felix11h.dev@gmail.com

# Custom vars
version:             1.0.0

gems: [jekyll-paginate, jekyll-sitemap]
paginate: 8
paginate_path: "page:num"

